replicaCount: 3
service:
    type: NodePort
    port: 5000
    targetPort: 5000
container:
    name: sample-flask-app
    image: tanmayakp/sample-web-app:main-v1
autoPromote: false
canaryTraffic: 0
stableTraffic: 100
domain: flask.havefish.ml
gateway: default-gateway
routeName: primary

