replicaCount: 3
service:
    type: NodePort
    port: 5000
    targetPort: 5000
container:
    name: sample-web-app
    image: tanmayakp/sample-web-app:main-v3
autoPromote: false
greenHost: www.havefish.ml
blueHost: preview.havefish.ml
gateway: default-gateway

