replicaCount: 3
service:
    type: NodePort
    port: 5000
    targetPort: 5000
container:
    name: sample-web-app
blueContainer:
    image: tanmayakp/sample-web-app:main-v3
    state: enabled
greenContainer:
    image: tanmayakp/sample-web-app:main-v2
    state: enabled
    
autoPromote: false
activeHost: www.havefish.ml
inactiveHost: preview.havefish.ml
gateway: default-gateway
inactive: green


