apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.container.name }}-vsvc
spec:
  gateways:
  - {{ .Values.gateway }}
  hosts:
  - {{ .Values.domain }}
  http:
  - name: {{ .Values.routeName }}  
    route:
    - destination:
        host: {{ .Values.container.name }}  
      weight: {{ .Values.stableTraffic }}
    - destination:
        host: {{ .Values.container.name }}-canary  
      weight: {{ .Values.canaryTraffic }}
